### ISSUE TITLE
Add error checks for both input and output

### ISSUE THREAD

**Issue by skeeto** [dbro/csvquote#18]
Input may end early due to an error and should be checked. More importantly, a successful `fwrite()` only means bytes were successfully copied to the output buffer. They may still fail to be written later when the buffer is flushed. Flushing at the end and checking its result ensures the output buffer has been emptied. Without this check, some write errors go undetected:

    echo | csvquote >/dev/full && echo success

[0001-Add-error-checks-for-both-input-and-output.patch.txt](https://github.com/dbro/csvquote/files/7697299/0001-Add-error-checks-for-both-input-and-output.patch.txt)
```diff
--- a/csvquote.c
+++ b/csvquote.c
@@ -94,6 +94,8 @@ const char del, const char quo, const char rec) {
         check(fwrite(buffer, sizeof(char), nbytes, stdout) == nbytes,
             "Failed to write %zu bytes\n", nbytes);
     }
+    check(ferror(in) == 0, "Failed to read input\n");
+    check(fflush(stdout) == 0, "Failed to flush output\n");
     return 0;
 
 error:
```

**Comment by dbro** [comment]
Thanks, commited with https://github.com/dbro/csvquote/commit/83ac568df9ef2be5f9ee2321d60a1c7dffd79833

**Comment by dbro** [comment]
And thank you for your excellent [write-up](https://nullprogram.com/blog/2021/12/04/) describing how you wrote a much faster version of csvquote. The part about removing the third state from the machine was especially appreciated. I learned quite a few things -- "naive" is an apt way to describe my skills.

A quick benchmark using this [example dataset of 500k quotes](https://github.com/ShivaliGoel/Quotes-500K) shows a speedup from 1.03 seconds to 0.31 seconds for me. I should mention that I needed to disable SIMD using the -O3 flag for my system, which is already about 8 years old today.

I'd like to encourage people to benefit from your code. Would you be interested in creating a standalone repo for it that I could point people to from /dbro/csvquote ? Or would you prefer me to replace the code in this repo with yours? I think the only important change I would suggest would be to add support for tab-delimited input and output.
