### ISSUE TITLE
working with body

### ISSUE THREAD

**Issue by ppKrauss** [dbro/csvquote#7]
To work with [datasets](https://github.com/datasets) as [country-codes.csv](https://github.com/datasets/country-codes/blob/master/data/country-codes.csv) we need some more workaround. The simple "sort by column3" is,

  `cat country-codes.csv | (read -r; printf "%s\n" "$REPLY"; csvquote | sort -t , -k 3,3 | csvquote -u) > byCol3.csv`

So, perhaps you can build a shell complement to work in a simple syntax, as [`csvsort`  command](http://csvkit.readthedocs.org/en/0.9.1/scripts/csvsort.html).

-----

PS: I have problems with [csvkit](https://github.com/onyxfish/csvkit/issues/458), and, as [suggested here](https://github.com/rgrp/command-line-data-wrangling) back to usual unix commands... But need simple command, as [suggested here](http://unix.stackexchange.com/a/11859/130402) (but not works fine and I using [this ugly](http://unix.stackexchange.com/a/11857/130402)).

**Comment by dbro** [comment]
If I understand you correctly, the first line of the data file country-codes.csv contains the labels of the fields, and you would like your output file to keep that as the first line. The remaining lines would be sorted by the value in the 3rd field.

The command you suggest is an appropriate solution that composes various unix shell commands, not what I would call a "workaround." You could create a wrapper around this compound command, following the example shown by the csvheader script in this repository. However I don't think it's necessary to include it in this repository. The aim of csvquote is to do one thing, and to be ready to work with other unix commands as you've demonstrated.
